### ISSUE TITLE
Tidy up subscriber selection algorithm

### ISSUE THREAD

**Issue by davidben** [davidben/tls-trust-expressions#19]
I think we're a bit too prescriptive in the subscriber behavior section:
https://davidben.github.io/tls-trust-expressions/draft-davidben-tls-trust-expr.html#name-subscriber-behavior

Specifically, it's written as if you first look for a TE-based match, then you consider other stuff like CA. Instead, I think the right model is:

* Here is how you use TE to get a positive signal of trust anchor match. TE might tell you "yes, it matches" or "unknown"
* The `certificate_authorities` extension can also give you a similar signal.
* Other extensions might be defined later to similarly handle trust negotiation
* If any such extension says "yes, it matches", you have a trust anchor match. Otherwise it's unknown whether the server trusts the path.

From there, the subscriber has free reign to decide how it selects a credential based on this "trust anchor match" signal. One possible scheme (but not the only one) is:

* Subscriber maintains a list of credentials, in preference order, e.g. sorted by size or speed of signing key
* Some credentials require a trust anchor match, presumably the ones at the front of the queue
* Other credentials skip this check because they're fallback credentials, presumably the ones at the end of the queue
* Pick the first credential that matches

**Comment by martinschmatz** [comment]
Just FYI: I was playing around with the idea to pack the information intended to be transported in the proposed new `trust_expressions` extension in "fake" root certs which can be sent to the subscriber using the _existing_ `certificate_authorities` extension "which SHOULD be used by the receiving endpoint to guide certificate selection" as per [RFC](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.4) (read: The server is free how to use the information). 

It is easy to create a self signed "root cert" with some base64 encoded information in CN etc fields to help the subscriber in the selection of the certificate chain to use for authentication.

**Comment by davidben** [comment]
Hi @martinschmatz, thanks for the comment. As this has nothing to do with this issue, I've filed https://github.com/davidben/tls-trust-expressions/issues/23 so we can move the discussion there.

**Comment by martinschmatz** [comment]
Sure @davidben - I added it here because it might be that the first two bullets above could merge, thereby avoiding the hassle to convince people to change the TLSv1.3 RFC. 

Joining #23
