### ISSUE TITLE
Packing trust_expressions into certificate_authorities

### ISSUE THREAD

**Issue by davidben** [davidben/tls-trust-expressions#23]
@martinschmatz wrote the following on https://github.com/davidben/tls-trust-expressions/issues/19#issuecomment-2137282741

> Just FYI: I was playing around with the idea to pack the information intended to be transported in the proposed new `trust_expressions` extension in "fake" root certs which can be sent to the subscriber using the _existing_ `certificate_authorities` extension "which SHOULD be used by the receiving endpoint to guide certificate selection" as per [RFC](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.4) (read: The server is free how to use the information). 
>
> It is easy to create a self signed "root cert" with some base64 encoded information in CN etc fields to help the subscriber in the selection of the certificate chain to use for authentication. 

Moving this to a separate issue as issue #19 is about something completely unrelated.

@martinschmatz, could you perhaps expand on this? I don't see what benefit it would have, but some of the details don't make sense to me, so perhaps I am misunderstanding.

First, the `certificate_authorities` extension doesn't carry certificates but names. So there wouldn't be a root certificate in the first place. Base64 encoding also sounds like unnecessarily wasteful (keep in mind we want a compact scheme), though one could use a new OCTET-STRING-carrying attribute. That would still be wasteful with the rest of the ASN.1 structure, but much less so.

Second, even though RFC 8446 does not prescribe a precise way to use the information, no one implements a trust expressions matching algorithm with it today. They'll all do some variation of checking for a matching issuer among the relying party's list, because those are the semantics of the field. The allowance is because there are lots of ways to do that and integrate it with other processes.

If we were to imbue an existing field with new semantics, we're going to need a code change in the TLS stack anyway. (And, to reduce server operator burden, I think it's important that the matching algorithm be in the TLS stack, at least long-term.) At that point, there is no cost to using a new extension, so we may as well define an extension with the right semantics.

Finally, there is a real cost to jamming new semantics into existing fields. In addition to the wasteful encoding, this risks weird behaviors when existing software interprets the field according to its existing semantics.

**Comment by martinschmatz** [comment]
While I value your effort towards better [crypto-]agility, I'm concerned that it'll take many years for those features to reach OS dist packages. I most certainly support your view that a server should have several cert chains available and adaptively select one pending information received by the client during TLS handshake. 

I therefore played around with a [much] simpler approach by sneaking information into the `certificate_authorities` extension. This explicitly not with the desire to increase agility, but to nevertheless help in the selection of the several available cert chains.

As a super simplified example, let's assume a "fake" root cert is built like this: 
```
SIGALG_default=prime256v1
openssl ecparam -genkey \
                -name $SIGALG_default \
                -noout \
                -out CA_default.key \
&& \
openssl req \
                -config /etc/pki/tls/openssl.cnf \
                -key CA_default.key \
                -subj '/ST=I want purely QSC cert chain/L=Please use Germany as geo/CN=I want sec level 5' \
                -new \
                -x509 \
                -days 7300 \
                -extensions v3_ca \
                -out CA_default.crt
```

The `-subj` line is the place where cert-chain-selection-hints are added. As you can see, I expect a reasonably small, highly pragmatic set of selection parameters
- Legacy, QSC, Hybrid sigalgs
- The geo will give a good hint about mandated algs 
- The security level is key for interactions with gov
- Potentially some very few more 

Few comments to the above: 
- 'cost' is small: The above adds 110 Bytes to a `ClientHello` in the `certificate_authorities` extension and can be further reduced quite a bit by anyway preferred "code points" (`-subj '/ST=0x2345/L=Ox4444/CN=0x0005'` adds 57 bytes only) 
- Per request specification of `signature_algorithms` extension can not be expected to be easily supported by the gazillion of client apps, while a general description of what the client expects will not necessarily change between requests.
- Implicitly, I'm expecting a gradual, but at least initially slow growth of CAs to support Q-safe root certs. Clients will then have two cert bundles, one legacy and one Q-safe. And it'll be the clients responsibility to have the 'usual suspects' CA for the features the client is asking in its cert bundle.
- Yes, servers must implement code changes, but the clients not. 

As for the specific use of "fake root certs" for the `certificate_authorities` extension in the TE context: In the mean time, I have the suspicion that the entries in your `trust_expressions` extensions might quite likely exceed (?) the max number of characters for the x509 fields transported via `certificate_authorities` extension. It would therefore not be a valid option for TE.

**Comment by davidben** [comment]
Closing this as I don't think we want to overload the existing `certificate_authorities` extension with completely different semantics.
