### ISSUE TITLE
Does CertificatePropertyList confer any semantics on its own?

### ISSUE THREAD

**Issue by davidben** [davidben/tls-trust-expressions#6]
In prototyping some subscriber support, one thing came up: trust-expression-enabled credentials are different from normal credentials:

* The credentials are expected to be gated on trust expressions, or some other kind of issuer negotiation. (You could imagine also checking the `certificate_authorities` extension, or other mechanisms.)
* Due to this negotiation, the credentials are expected be exact certificate paths, with nothing extra or missing. In particular, this means it should be safe for the subscriber to check against the `signature_algorithms` and `signature_algorithms_cert` without worrying about stray MD2 self-signed roots.

However, CertificatePropertyList is extensible, which is nice because it allows us to introduce other kinds of properties without changing the CA -> server software -> TLS library flow. It's basically a grab-bag of any kind of CA -> server software communication.

But this, combined with wanting to minimize how much layers in between need to inspect CertificatePropertyList puts us in a pickle: what does it mean if you get a CertificatePropertyList without any trust expression property? Maybe it's got some other property you don't understand. Does it still imply that it's still issuer-gated and a whole path?

If yes, the extensibility is less useful. There may well be use cases that don't want to be issuer-gated.
If no, we don't want the certificate to accidentally get interpreted as non-issuer-gated when it actually was issuer-gated by some other mechanism.

In writing this, I think I'm coming around to "no" being the right answer, but then...
* Should the caller be required to call some "this is an issuer-gated credential" API? I.e. we use an out-of-band signal rather than relying on in-band signals that might disappear.
* Do we have a general "this is issuer-gated" property and say everyone must understand this? That seems a bit weird.
* Do we need to invent critical properties??? 😭

**Comment by bwesterb** [comment]
What about:

1. If there is a trust expression property, ignore other properties you don't understand.
2. If there are no properties you understand, ignore the credential.

New properties can define different semantics as desired.

**Comment by davidben** [comment]
What if, say, we moved SCT lists to a certificate property (could be a convenient way for the CA to deliver them and allow the server to negotiate which to send)? If you see only that property, do you ignore the credential?

Bob, Devon, and I talked a bit about this earlier and are currently leaning towards the first of the three options: CPLs are just a bag of data, and it's on the TLS library user to say "this credential needs to match the issuer" and "I believe this credential is ubiquitous and a viable candidate for the default".

It does make the API a bit more annoying, but that does ultimately translate to what probably the application's config file will be: a new directive for "here are my negotiated certs". (Or "here are some ACME URLs to get negotiated certs".) You need a new one mostly because the existing one has an implicit "this is ubiquitous" semantic.

**Comment by davidben** [comment]
Forgot this was open, but I think we've mostly settled on the interpretation above. https://github.com/davidben/tls-trust-expressions/pull/21 makes this a bit more explicit too in its example. Leaving this open just because we probably do need some text on the implications for the ACME bits.

**Comment by davidben** [comment]
Think I'll just close this. Not sure what ACME text I was thinking and probably wouldn't belong in this doc anyway.
