### ISSUE TITLE
Trust anchor identifier is limited to 255 bytes

### ISSUE THREAD

**Issue by bwesterb** [davidben/tls-trust-expressions#65]
If defined as a relative OID to PEN, then the maximum length is 610 bytes (128-6 max depth times 5 bytes for 2^32-1). Implicitly, you restrict to 255 bytes by its TLS encoding. Better make that requirement explicit in §3 or lift it.

**Comment by davidben** [comment]
I'm not sure OIDs are actually limited, in either depth or component size. Implementations often apply limits for practicality and DoS, but my understanding was that the data type itself is unbounded.

TLS doesn't really do variable-length length prefixes, and keeping the length prefix at 1 byte is useful, so I don't think we should raise the limit. Also if you get anywhere near 255 bytes, you're probably doing something wrong. But yeah, we could include a sentence to the effect of "there's a protocol limit in TLS of 255 bytes but really you shouldn't get anywhere close to this".

**Comment by bwesterb** [comment]
You're right — the limit quoted is SMIv2.

**Comment by davidben** [comment]
https://github.com/davidben/tls-trust-expressions/pull/66
