### ISSUE TITLE
Rename "subscriber" to "authenticating party"

### ISSUE THREAD

**Issue by davidben** [davidben/tls-trust-expressions#74]
We took "subscriber" from the BRs but it's referring to a subscriber/applicant to the CA. That's not wrong but is a little confusing in the context of this protocol.

"Relying party" and "authenticating party", while a mouthful, has a nice symmetry to it.

**Comment by devonobrien** [comment]
+1 to moving off subscriber and onto authenticating party, even if it is a mouthful. This will undoubtedly get re-litigated post-adoption, so we should just get onto a terminology that's less actively confusing than subscriber.

**Comment by davidben** [comment]
Haha, I see we previously wrote this, which "authenticating" in the other direction. (I'll just rephrase this.)

> Subscriber: : The party whose identity is being validated in the protocol. In TLS, this is the side sending the Certificate and CertificateVerify message.
>
> Relying party: : The party authenticating the subscriber. In TLS, this is the side that validates a Certificate and CertificateVerify message.
